config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :books
  match '/download_books', to: 'books#download', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book , only: [:show, :edit, :update, :destroy]
  before_action :set_books, only: [:index, :download]
  # GET /books
  # GET /books.json
  def index
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    #Crea un excel en la carpeta public
    workbook  = WriteXLSX.new('public/Books.xlsx')
    worksheet = workbook.add_worksheet


    header_format = workbook.add_format(font: "Arial", size: 12, align: "center")
    header_format.set_text_wrap()
    header_format.set_bold
    header_format.set_bg_color("#DFF0D8")
    header_format.set_color("#008857")

    worksheet.set_column('A:A', 45)
    worksheet.set_column('B:B', 45)
    worksheet.set_column('C:C', 45)

    #Encabezados
    #(fila , columna, encabezado)
    worksheet.write(0, 0, ' Titulo ',header_format)
    worksheet.write(0, 1, ' Autor ' ,header_format)
    worksheet.write(0, 2, ' Genero ',header_format)

    #Indices
    fila = 1
    columna = 0

    #Escribe los datos de la bdd
    @books.each do |book|
      worksheet.write(fila, columna       , book.title  )
      worksheet.write(fila, columna + 1   , book.author )
      worksheet.write(fila, columna + 2   , book.genre  )

      #Avanza una fila
      fila += 1
    end

    #Cierra el archivo
    workbook.close()

    #descarga el archivo
    File.open("public/Books.xlsx", "r") do |f|
     send_data f.read, :filename => "Books.xlsx", type: "application/xlsx"
    end

    #Elimina el archivo de la carpet public
    File.delete("public/Books.xlsx")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_books
      @books = Book.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>


<p id="notice"><%= notice %></p>

<h1>Books</h1>
<input id="archivo_cargado" type="file" />
  <button type="button"  onclick="importar_excel()"> importar </button>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
<br>
<%= link_to 'excel', download_books_path ,target: '_blank' %>


<script>
  function importar_excel(){
    // Obtiene el archivo cargado
    var archivo_seleccionado = document.getElementById("archivo_cargado").files;
    var valor_data64 = ""

    // Utilizar la posicion 0 es suficiente
    // contiene todo el archivo
    var fileToLoad = archivo_seleccionado[0];

    // Leer archivo
    var fileReader = new FileReader();

    // onload es ejecutado cuando el  contenido es leído
    fileReader.onload = function(fileLoadedEvent){

      // Contenido en formato base 64
      valor_data64 = fileLoadedEvent.target.result
      valor_data64 = valor_data64.replace("data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,", "").replace("data:application/xlsx;base64,", "")

      // Crear el objeto xlsx
      var objeto_xlsx = xlsx(valor_data64);
      book = objeto_xlsx.worksheets[0].data

      message = ""
      // Filas del excel
      for (var fila = 0; fila < book.length ; fila++) {
        // Columnas del excel
        for (var columna = 0; columna < book[fila].length; columna++) {
          console.log(book[fila][columna].value)
          message = message + book[fila][columna].value + "\n"
        }
      }
      alert(message)
    }

    // El método readAsDataURL es usado para leer el contenido del
    // especificado Blob o File.
    fileReader.readAsDataURL(fileToLoad);
  }

</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WriteExcel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>